<?php require_once 'includes/auth.php'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Blog Entries | UIU Talent Show</title>
  <link rel="stylesheet" href="assets/css/style.css" /><link rel="stylesheet" href="assets/css/pages/blog.css" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" /><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
</head>
<body class="category-page blog-page">
  <?php include "includes/header.php"; ?>
  <main class="category-main"><div class="page-heading"><p class="hero-badge"><i class="fas fa-pen-nib"></i> Creative showcase</p><h1>Blog Entries</h1><p>Stories, essays, and photo journals written by UIU students.</p></div><section class="content-section active-tab"><div class="blog-grid">
    <article class="blog-card"><div class="blog-header"><img src="https://i.pravatar.cc/40?img=33" class="avatar-lg" alt="Nusrat Jahan" /><div><h4 class="blog-author">Nusrat Jahan</h4><span class="blog-date"><i class="far fa-calendar"></i> Sep 1, 2026</span></div><span class="cat-badge blog-badge"><i class="fas fa-pen-nib"></i> Blog</span></div><h3 class="blog-title">A Weekend in Rangamati</h3><p class="blog-excerpt">The misty hills, crystal blue lake, and tribal culture of Rangamati left an unforgettable mark on my soul. Here is my story...</p><div class="blog-photos"><div class="blog-photo-item"><img src="https://picsum.photos/seed/blog1a/300/200" alt="Rangamati lake" /><p class="photo-desc">Kaptai Lake at sunrise - golden reflections on still water</p></div><div class="blog-photo-item"><img src="https://picsum.photos/seed/blog1b/300/200" alt="Rangamati hills" /><p class="photo-desc">The misty green hills surrounding the lake</p></div><div class="blog-photo-item"><img src="https://picsum.photos/seed/blog1c/300/200" alt="Tribal culture" /><p class="photo-desc">Local artisan crafting traditional tribal jewelry</p></div></div><div class="card-footer"><div class="reactions"><button aria-label="React" class="react-btn like-btn" onclick="likePost(this)"><i class="far fa-heart"></i> <span>88</span></button><button aria-label="React" class="react-btn comment-btn" onclick="openComments(this)"><i class="far fa-comment"></i> <span>34</span></button></div><div class="points-badge"><i class="fas fa-star"></i> <span>220</span> pts</div></div><div class="comments-panel hidden"><div class="comment-list"></div><div class="comment-input-row"><input class="comment-input" placeholder="Add a comment..." /><button aria-label="Send" class="send-btn" onclick="addComment(this)"><i class="fas fa-paper-plane"></i></button></div></div></article>
    <article class="blog-card"><div class="blog-header"><img src="https://i.pravatar.cc/40?img=40" class="avatar-lg" alt="Omar Faruq" /><div><h4 class="blog-author">Omar Faruq</h4><span class="blog-date"><i class="far fa-calendar"></i> Sep 2, 2026</span></div><span class="cat-badge blog-badge"><i class="fas fa-pen-nib"></i> Blog</span></div><h3 class="blog-title">The Life of a UIU Night Owl</h3><p class="blog-excerpt">Late-night study sessions, instant noodles, and unexpected friendships - the untold story of every CS student at 3 AM...</p><div class="blog-photos"><div class="blog-photo-item"><img src="https://picsum.photos/seed/blog2a/300/200" alt="night study" /><p class="photo-desc">The library at midnight - only the dedicated remain</p></div><div class="blog-photo-item"><img src="https://picsum.photos/seed/blog2b/300/200" alt="campus night" /><p class="photo-desc">UIU campus in the quiet hours of the night</p></div></div><div class="card-footer"><div class="reactions"><button aria-label="React" class="react-btn like-btn" onclick="likePost(this)"><i class="far fa-heart"></i> <span>115</span></button><button aria-label="React" class="react-btn comment-btn" onclick="openComments(this)"><i class="far fa-comment"></i> <span>47</span></button></div><div class="points-badge"><i class="fas fa-star"></i> <span>275</span> pts</div></div><div class="comments-panel hidden"><div class="comment-list"></div><div class="comment-input-row"><input class="comment-input" placeholder="Add a comment..." /><button aria-label="Send" class="send-btn" onclick="addComment(this)"><i class="fas fa-paper-plane"></i></button></div></div></article>
    <article class="blog-card"><div class="blog-header"><img src="https://i.pravatar.cc/40?img=45" class="avatar-lg" alt="Zara Ahmed" /><div><h4 class="blog-author">Zara Ahmed</h4><span class="blog-date"><i class="far fa-calendar"></i> Sep 3, 2026</span></div><span class="cat-badge blog-badge"><i class="fas fa-pen-nib"></i> Blog</span></div><h3 class="blog-title">My First Photography Exhibition</h3><p class="blog-excerpt">From clicking on a phone camera to exhibiting at a university gallery - this is how a hobby became a passion...</p><div class="blog-photos"><div class="blog-photo-item"><img src="https://picsum.photos/seed/blog3a/300/200" alt="photography" /><p class="photo-desc">First roll of film ever developed - blurry but precious</p></div><div class="blog-photo-item"><img src="https://picsum.photos/seed/blog3b/300/200" alt="exhibition" /><p class="photo-desc">The gallery wall with 12 of my best prints</p></div><div class="blog-photo-item"><img src="https://picsum.photos/seed/blog3c/300/200" alt="camera" /><p class="photo-desc">My trusty DSLR that started the whole journey</p></div></div><div class="card-footer"><div class="reactions"><button aria-label="React" class="react-btn like-btn" onclick="likePost(this)"><i class="far fa-heart"></i> <span>73</span></button><button aria-label="React" class="react-btn comment-btn" onclick="openComments(this)"><i class="far fa-comment"></i> <span>28</span></button></div><div class="points-badge"><i class="fas fa-star"></i> <span>185</span> pts</div></div><div class="comments-panel hidden"><div class="comment-list"></div><div class="comment-input-row"><input class="comment-input" placeholder="Add a comment..." /><button aria-label="Send" class="send-btn" onclick="addComment(this)"><i class="fas fa-paper-plane"></i></button></div></div></article>
  </div></section></main>
  <?php include "includes/footer.php"; ?><script src="assets/js/main.js"></script>
</body>
</html>