<?php require_once 'includes/auth.php'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Competitions | UIU Talent Hunter</title>
  <link rel="stylesheet" href="assets/css/style.css" /><link rel="stylesheet" href="assets/css/pages/competitions.css" />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" /><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
</head>
<body class="category-page competitions-page">
  <?php include "includes/header.php"; ?>
  <main class="competition-page-main"><header class="page-heading"><p class="hero-badge"><i class="fas fa-trophy"></i> Find your arena</p><h1>Competitions</h1><p>Enter the arena. Prove your talent to the world.</p></header><div class="competition-filter"><button class="filter-btn active"><i class="fas fa-border-all"></i> All</button><button class="filter-btn"><i class="fas fa-video"></i> Video</button><button class="filter-btn"><i class="fas fa-music"></i> Audio</button><button class="filter-btn"><i class="fas fa-align-left"></i> Text</button></div><section class="competition-list">
    <article class="full-competition-card"><img src="https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=640&h=240&fit=crop&auto=format" alt="Dancers performing on stage" /><div class="full-competition-body"><span class="competition-type">Dance Competition</span><h2>International Fusion Dance Championship</h2><p>Bring your unique dance style to the global stage. This championship welcomes classical, contemporary, hip-hop, folk, and fusion.</p><div class="details-grid"><div><b>Aug 1, 2026</b><span>Start Date</span></div><div><b>Sep 15, 2026</b><span>End Date</span></div><div><b>Free</b><span>Entry Fee</span></div><div><b>$3,000</b><span>Prize</span></div></div><a class="btn-primary" href="index.php#home">Register Now</a></div></article>
    <article class="full-competition-card"><img src="https://images.unsplash.com/photo-1485846234645-a62644f84728?w=640&h=240&fit=crop&auto=format" alt="Actor performing on a stage" /><div class="full-competition-body"><span class="competition-type">Acting Competition</span><h2>UIU Stage &amp; Screen Acting Awards</h2><p>Prove your craft in front of industry judges with a monologue, scene, or original piece.</p><div class="details-grid"><div><b>Aug 10, 2026</b><span>Start Date</span></div><div><b>Sep 30, 2026</b><span>End Date</span></div><div><b>Free</b><span>Entry Fee</span></div><div><b>$2,500</b><span>Prize</span></div></div><a class="btn-primary" href="index.php#home">Register Now</a></div></article>
    <article class="full-competition-card"><img src="https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=640&h=240&fit=crop&auto=format" alt="Musician performing with a microphone" /><div class="full-competition-body"><span class="competition-type">Music Competition</span><h2>UIU Music Fest - Emerging Artists Showcase</h2><p>From acoustic sets to full-band performances, original compositions to reimagined classics.</p><div class="details-grid"><div><b>Aug 5, 2026</b><span>Start Date</span></div><div><b>Oct 1, 2026</b><span>End Date</span></div><div><b>Free</b><span>Entry Fee</span></div><div><b>$4,000</b><span>Prize</span></div></div><a class="btn-primary" href="index.php#home">Register Now</a></div></article>
    <article class="full-competition-card"><img src="https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=640&h=240&fit=crop&auto=format" alt="Colorful painting on a canvas" /><div class="full-competition-body"><span class="competition-type">Art Exhibition</span><h2>Canvas &amp; Beyond - Painting Showcase</h2><p>Submit your finest oil, watercolour, digital, or mixed-media work and share your vision.</p><div class="details-grid"><div><b>Jul 20, 2026</b><span>Start Date</span></div><div><b>Sep 20, 2026</b><span>End Date</span></div><div><b>Free</b><span>Entry Fee</span></div><div><b>$2,000</b><span>Prize</span></div></div><a class="btn-primary" href="index.php#home">Register Now</a></div></article>
    <article class="full-competition-card"><img src="https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=640&h=240&fit=crop&auto=format" alt="Camera ready for a photography shoot" /><div class="full-competition-body"><span class="competition-type">Photography Contest</span><h2>Lens Masters Photography Competition</h2><p>Capture this year's theme, Human Connection, through authentic images and emotional storytelling.</p><div class="details-grid"><div><b>Aug 15, 2026</b><span>Start Date</span></div><div><b>Oct 10, 2026</b><span>End Date</span></div><div><b>Free</b><span>Entry Fee</span></div><div><b>$3,500</b><span>Prize</span></div></div><a class="btn-primary" href="index.php#home">Register Now</a></div></article>
    <article class="full-competition-card"><img src="https://images.unsplash.com/photo-1455390582262-044cdead277a?w=640&h=240&fit=crop&auto=format" alt="Notebook and pen for writing" /><div class="full-competition-body"><span class="competition-type">Writing Competition</span><h2>UIU Literary Excellence Awards</h2><p>Submit a short story, poem, personal essay, or flash fiction and compete for recognition.</p><div class="details-grid"><div><b>Sep 1, 2026</b><span>Start Date</span></div><div><b>Nov 1, 2026</b><span>End Date</span></div><div><b>Free</b><span>Entry Fee</span></div><div><b>$2,000</b><span>Prize</span></div></div><a class="btn-primary" href="index.php#home">Register Now</a></div></article>
  </section></main>
  <?php include "includes/footer.php"; ?>
  <script src="assets/js/main.js"></script>
</body>
</html>